name: "deploy para VPS"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - name: "baixar o codigo"
        uses: action/chekout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v1
        with:
        host: "82.25.74.36"
        username: "root"
        key: ${{secrets.SERVER_SSH_KEY}}
        source: "."
        target: "/home/willian."

      - name: "buid da aplicação"
        uses: appleboy/ssh-action@v1
        with:
          host: "82.25.74.36"
          username: "root"
          key: ${{secrets.SERVER_SSH_KEY}}
          script: |
            cd /home/willian.
            composer install --no-dev --no-progress -a
            chown -R www-data:www-data .